### ISSUE TITLE
P15 - move to $$digestOnce kind of confusing - missing highlighting?

### ISSUE THREAD

**Issue by scottsilvi** [teropa/build-your-own-angularjs#147]
I'm working through round 2 of the book (giving a talk on Section 1 @ a meetup in town), and thought perhaps this example could be cleared up. There's no code highlighting, so while I grokked the change from $digest to $digestOnce, I missed the addition of the dirty variable. Even the preceding sentence doesn't explicitly describe it.

**Comment by teropa** [comment]
Thanks, I added highlighting for the changes in this section.
