### ISSUE TITLE
New attributes are not being denormalized correctly.

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#151]
If I understood correctly, having a directive like:

`<foo></foo>`

if I `$set` a new attribute to it like: `myAttr` it should add to the dom `my-attr` but actually it is adding `my_attr` which is wrong.

Test case:

```javascript
it('sets attributes to DOM using snake case with -', function() {
  registerAndCompile(
    'myDirective',
    '<my-directive></my-directive>',
    function(element, attrs) {
      attrs.$set('myAttr', '43');
      expect(element.attr('my-attr')).toEqual('43');
    }
  );
});
```

Solution (on page 446, later the code is extended but not fixed):

```javascript
if (!attrName) {
  if (this.$attr[key]) {
    attrName = this.$attr[key];
  } else {
    attrName = this.$attr[key] = _.snakeCase(key, '-');
  }
}
```

Cheers.

**Comment by teropa** [comment]
Thanks, I've fixed this. As we're moving to LoDash 3, we'll just use the built-in `_.kebabCase` method from now on.
