### ISSUE TITLE
P3 - How scopes are used

### ISSUE THREAD

**Issue by scottsilvi** [teropa/build-your-own-angularjs#152]
The first two bullets for how scopes are used are: 

• Sharing data between controllers and views
• Sharing data between different parts of the application

I feel like these are sort of redundant. Especially when you consider eventing, which also "shares data between different parts of the application". I don't know exactly what your intent was there, but perhaps updating it to be more explicit, and less generic, would be useful?

**Comment by teropa** [comment]
Rephrasing.
