### ISSUE TITLE
P35 - kicking off a digest in $evalAsync

### ISSUE THREAD

**Issue by scottsilvi** [teropa/build-your-own-angularjs#155]
Working through this, I think some clarity around the new $evalAsync function would be helpful

    if(!self.$$phase && !self.asyncQueue.length) {
        setTimeout(function () {
            if (self.$$asyncQueue.length) {
                self.$digest();
            }
        }, 0);
    }
    self.$$asyncQueue.push({ scope: self, expression: expr });

(For clarity): Ultimately what this function is doing is saying "if phase is null, and the $$asyncQueue is empty, let's go ahead and call setTimeout. We will then immediately add an item to the $$asyncQueue, before the setTimeout function is actually executed. When the setTimeout function is called, we will check to see if the $$asyncQueue has a length and, if so, call $digest."

I'm trying to understand the purpose of both of these conditionals. 

If you were to call $evalAsync twice in succession, outside of the digest cycle (so self.$$phase will be null), the first $evalAsync call will have an asyncQueue length of 0, so the conditional is true. It will then add an item to the asyncQueue length. When the 2nd $evalAsync call is made, the $$asyncQueue length is 1, and we don't call setTimeout. At some point down the road, setTimeout is called, our length is truthy, and the $digest cycle is fired. Correct?

As to the conditional inside setTimeout... Is that there in case a $digest (kicked off elsewhere) flushes the asyncQueue before setTimeout is called (which would then prevent a '$digest already in progress' error)? 

Do I have the right of this? Either way, it might be helpful to explain why these conditionals (pertaining to $$asyncQueue.length) both exist.

**Comment by hieudt** [comment]
Can anyone explain the purpose of the condition `!self.asyncQueue.length` in `if(!self.$$phase && !self.asyncQueue.length)` ? Why do we have to use it?

**Comment by teropa** [comment]
@hieudt If `self.asyncQueue.length` is not zero, it means `$evalAsync` has also been called earlier and we have already scheduled a digest, and we don't want to schedule another one. So the idea is to avoid doing the `setTimeout` several times unnecessarily.

**Comment by teropa** [comment]
Rephrasing some of this in upcoming release.

**Comment by caolinjian** [comment]
@scottsilvi  As to the conditional inside setTimeout,if $digest already in progress .why not use self.$$phase || self.asyncQueue.length
