### ISSUE TITLE
P47

### ISSUE THREAD

**Issue by runtimeZero** [teropa/build-your-own-angularjs#157]
Regarding "While we don’t expect that second watch to execute, we don’t expect an exception to be thrown either, which is what actually happens."

No exception was thrown. kindly recheck test code.

**Comment by rkurbatov** [comment]
Confirm. Modifying the test to catch exception fails it.

**Comment by teropa** [comment]
I'm getting an exception as described in the book. 

    'undefined' is not an object (evaluating 'watcher.watchFn')
