### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by odonnell-pb** [teropa/build-your-own-angularjs#171]
For windows installations: 
It might pay to note that python 2.7.3 is required.
Reference issue #88: atal error: spawn ENOENT (sic)

**Comment by sdesmond** [comment]
I ran across this too.  I believe it was Socket.io which is used by Testem.  When I tried to npm install testem, I found the "python needed" error in the log.  It just needs to be Python < 3.

**Comment by iliatcymbal** [comment]
Hi, guys! I've installed python 2.7.3, made changes from Reference issue #88, but still have the same issue (spawn ENOENT). What the next step to resolve it? :-)

**Comment by teropa** [comment]
No longer using Testem, so closing this.
