### ISSUE TITLE
P26 - Error on how $apply() invokes $digest()

### ISSUE THREAD

**Issue by hermagrini** [teropa/build-your-own-angularjs#187]
$apply actually calls $root.$digest(), not this.$digest(). This is a common misconception created by bad documentation, though now the angular team has added a pseudo-code to clarify this.

https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$apply

Cheers!

**Comment by teropa** [comment]
In Chapter 1 there's just one scope, so there's no `$root` yet. We switch to root digestion when scope inheritance is introduced in Chapter 2. This particular issue is addressed starting on P78.
