### ISSUE TITLE
Grunt: warning: grunt-contrib-watch not found

### ISSUE THREAD

**Issue by stefanscheidt** [teropa/build-your-own-angularjs#188]
I just cloned the repo, did
```
git checkout chapter0-project-setup
git checkout -b my-own-angular
npm install
grunt testem
```
and got a warning: `Local Npm module "grunt-contrib-watch" not found. Is it installed?`

Then I did `npm install grunt-contrib-watch --save-dev` with lot of `unmet dependency` warnings. But now `grunt testem` gives now warning.

**Comment by teropa** [comment]
Just did a fresh clone and followed your steps, and for me everything seemed to go fine.

`grunt-contrib-watch` is not used by the current version of the book, though it used to be. This leads me to think that maybe there's something wrong with the tags in our Git repo. Could you confirm if `chapter0-project-setup` points to 315916e933 for you?

**Comment by stefanscheidt** [comment]
Hi. I also made a fresh clone and did a checkout chapter0-project-setup with this result:

    HEAD is now at 315916e... Define The Default Grunt Task

I still got the same warning, but except for these warnings the test are passing.

Maybe this issue can simply be closed.

**Comment by teropa** [comment]
No longer using Grunt, closing.
