### ISSUE TITLE
$watchCollection for nested objects not working

### ISSUE THREAD

**Issue by sunny762** [teropa/build-your-own-angularjs#195]
don't know whether the $watchcollection functionality is supposed to work in the first place for nested objects ... seems like it should

   it("detects changes to nested objects", function() {
        scope.counter = 0;
        scope.obj = {
            a: {
                b: 1
            }
        };
        scope.$watchCollection(
            function(scope) {
                return scope.obj;
            },
            function(newValue, oldValue, scope) {
                scope.counter++;
            }
        );
        scope.$digest();
        expect(scope.counter).toBe(1);
        scope.obj.a.b = 2;
        scope.$digest();
        expect(scope.counter).toBe(2);
        scope.$digest();
        expect(scope.counter).toBe(2);
     });

**Comment by teropa** [comment]
`$watchCollection` does not work for nested objects, and is not designed to.

I recently contributed something that clarifies this to the Angular docs: https://docs.angularjs.org/guide/scope#scope-watch-depths

**Comment by ashvaibhav** [comment]
@teropa - great article. Thanks for sharing it.
But scope.$watch(expr, listener, true) doesn't seem to work (in Angular 1) for below code if `objArray[0].listItems[0].name` is changed:

```
var objArray = [
  {
    listItems: [{
      name: 'n1'
    }]
  }
]
```
