### ISSUE TITLE
P523 Mixed code snippet with Figure

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#203]
I don't think that putting a figure inside a test snippet is a good idea :P

**Comment by teropa** [comment]
My toolchain attempts to position images automatically in an optimal way. Will return to this for the final build(s) to see that the positions are good.

**Comment by Foxandxss** [comment]
Page 676 has this as well.

**Comment by teropa** [comment]
Upcoming release changes image positioning.
