### ISSUE TITLE
P738: a line is missing from the source code

### ISSUE THREAD

**Issue by pomerantsev** [teropa/build-your-own-angularjs#211]
A line has been introduced on P563: `isolateScope.$on('$destroy', unwatch);`
But it is not there both on P596 and [in the source code](https://github.com/teropa/build-your-own-angularjs/blob/067b999e788c85037c08a9af9786d7f111c189ae/src/compile.js#L473-474).

**Comment by teropa** [comment]
Fixed, thanks
