### ISSUE TITLE
P451 - "allows creating directives with object notation" fails

### ISSUE THREAD

**Issue by jbasiago** [teropa/build-your-own-angularjs#214]
I've been going through the book building up the tests and the code and found a problem at this point.  There is one change to the code that is omitted I believe, and I didn't find the change anywhere else in the book.  The problem is at this point, the code in injector.js/runInvokeQueue is still;

    function runInvokeQueue(queue) {
        _.forEach(queue, function (invokeArgs) {
            var service = providerInjector.get(invokeArgs[0]);
            var method = invokeArgs[1];
            var args = invokeArgs[2];
            service[method].apply(providerCache.$provide, args);
        });
    }

For the test to pass, the method needs to be changed to;

    function runInvokeQueue(queue) {
        _.forEach(queue, function (invokeArgs) {
            var service = providerInjector.get(invokeArgs[0]);
            var method = invokeArgs[1];
            var args = invokeArgs[2];
            service[method].apply(service, args);
        });
    }

Hope this helps.

**Comment by teropa** [comment]
Applied the change on P396 - thanks!
