### ISSUE TITLE
Lodash.js is missing

### ISSUE THREAD

**Issue by aviadlich** [teropa/build-your-own-angularjs#216]
At the project setup section adding lodash failed:
node_modules/lodash/lodash.js file did not exists on my environment.
Lodash version is 3.0.0
I had to copy the file from here:
node_modules/grunt/node_modules/lodash/lodash.js
Then it worked

**Comment by blacknash** [comment]
Lodash >= 3.0.0 installed with npm now have a "modern build", they change the name of the file from **lodash.js** to **index.js**

You only need to change this line:
`'node_modules/lodash/lodash.js',`

For this one : 

`'node_modules/lodash/index.js',`

**Comment by teropa** [comment]
@blacknash thanks, will update the book and example project to the latest LoDash soon

**Comment by kaiserkoenig** [comment]
Hi,

i tried index.js even before i read this issue... but it still doesn't work...

`Scope digest calls the listener function of a watch on first $digest
ReferenceError: Can't find variable: _ in http://localhost:7357/src/scope.js (line 32)
$digest@http://localhost:7357/src/scope.js:32:3
http://localhost:7357/test/scope_spec.js:41:17`

**Comment by teropa** [comment]
Update coming up in the next release.
