### ISSUE TITLE
p329 module loading description

### ISSUE THREAD

**Issue by dishui** [teropa/build-your-own-angularjs#217]
on page 329, we have this paragraph:

"When you register a module with the same name several times, the new module replaces any old ones. This also means that when we call module twice with the same name, it’ll give us a dierent module object each time:"  
I think there is a logical flaw here, maybe a typo?  It can be rewritten in either way below:

shouldn't it be:  
When you register a module with the same name several times, the new module replaces any old ones. This also means that when we call module twice with the same name, it should not give us a dierent module object each time:

or 
When you register a module with the same name several times, the new module does not replaces any old ones. This also means that when we call module twice with the same name, it’ll give us a dierent module object each time:

**Comment by teropa** [comment]
I think the description is logically sound, but I reworded it slightly to make it more clear.
