### ISSUE TITLE
P56 - Forgot to pass scope to listenerFn

### ISSUE THREAD

**Issue by fvanwijk** [teropa/build-your-own-angularjs#225]
When calling the `listenerFn` in `Scope.prototype.$watchGroup`, you forgot to pass the scope as third argument. This is corrected in the updated `$watchGroup` implementation on P58, but confused me a bit.

Also you need to switch `oldVales` and `newValues` (`newValues` first).

**Comment by teropa** [comment]
Fixed, thanks
