### ISSUE TITLE
P68 missing describe block

### ISSUE THREAD

**Issue by sdesmond** [teropa/build-your-own-angularjs#229]
The description of `test/scope_spec.js` is inaccurate here.  On P58, you create a new describe block for `$watchGroup` so at this point, we actually have

    describe("Scope", function() {
      describe("digest", function() {
        // Tests from the previous chapter...
      });
      describe("$watchGroup", function() {
        // other tests from previous chapter...
      });
      describe("inheritance", function() {
        // Tests for this chapter
      });
    });

Also, in my opinion, most of the tests from chapter one should be in the `Scope` describe block and not in the `digest` (rename to `$digest`?) block since most of them have to do with `Scope` and not `$digest` in particular (e.g. it's `Scope` which "executes $eval'ed function and returns result", or "executes $apply'ed function and starts the digest", etc.).

**Comment by fvanwijk** [comment]
Possible duplicate of #34.

**Comment by sdesmond** [comment]
The first part that references the current state of the book stands.  In regards to the need to split up the tests, yes that is a duplicate.

**Comment by teropa** [comment]
Fixed the issue with the missing describe. Will do more reorganization as I do the chapter splitting. Thanks!
