### ISSUE TITLE
P87 - $applyAsync test on isolated scopes

### ISSUE THREAD

**Issue by rusilko** [teropa/build-your-own-angularjs#231]
Consider adding a test case for verifying that applyAsync'ed jobs are coalesced when called on different isolated scopes. I got this covered with following test case, although I am not sure if this is the correct approach because it also fails on not-isolated scopes before implementing code from pages 88-89.

```javascript
it("coalesces $applyAsync functions on isolated scopes", function(done) {
  var parent = new Scope();
  parent.counter = 0;
  var child = parent.$new(true);
  var child2 = parent.$new(true);
  parent.$watch(
    function(scope) { scope.counter++; }
  );
  child.$applyAsync(function(scope) {});
  child2.$applyAsync(function(scope) {});
  setTimeout(function() {
    expect(parent.counter).toBe(2);
    done();
  }, 50);
});
```

**Comment by teropa** [comment]
Thanks, I think I'll add this in a future update.

**Comment by teropa** [comment]
Adding.
