### ISSUE TITLE
The project setup link send you to a wrong place

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#234]
So using adobe reader for example, if you click (On the highlighted node):

![](http://puu.sh/h2cFC/fe334996f2.png)

It sends you to page 1 instead of page VII.

Same occurs if you click on here:

![](http://puu.sh/h2cIB/d085915206.png)

Not sure if that is in your range or the build tools you use for the book.

**Comment by Foxandxss** [comment]
I knew I opened an issue about this.

I realized that every link in there sends me tot he previous link. So in that case to reach "Create the project directories" I need to click "Create package.json for NPM"

**Comment by teropa** [comment]
Upcoming release should have a working ToC, thanks
