### ISSUE TITLE
PXIV Lodash variable '_' is undefined

### ISSUE THREAD

**Issue by sergeromero** [teropa/build-your-own-angularjs#235]
I just started following the book and just after installing lodash and jQuery and changing the Hello World function I get an error on testem saying:

Can't find variable: _ in http://localhost:7357/src/hello.js

At this time the lodash version is 3.6.0
The package.json file seems to be fine since the dependency is in the "dependencies" section instead of the "devDependencies" one.

I've read this section several times to make sure I didn't miss anything.

Thank you.

**Comment by sergeromero** [comment]
Forgot to mention that I had already added the necessary line in the Grunfile.js file:

serve_files: [
	'node_modules/lodash/index.js',
	'node_modules/jquery/dist/jquery.js',
	'node_modules/sinon/pkg/sinon.js',
	'src/**/*.js',
	'test/**/*.js'
]

So even with this which should get rid of this problem I was still getting the same error.

Apparently the problem was that I had the testem window opened when I did those changes. It worked after I closed and re-opened it.

**Comment by teropa** [comment]
That sounds like it might be from JSHint. Do you have `_: false` in the JSHint globals config?

**Comment by samwiseduzer** [comment]
I'm having the same problem

**Comment by samwiseduzer** [comment]
It appears that lodash 3.7.0, as it is in the npm repo, doesn't have a lodash.js file anymore. However, none of the .js files I can find seem to work either...

**Comment by cthulhu94401** [comment]
Same Issue.  Here is the error code:
Hello says hello
    ✘ ReferenceError: Can't find variable: _ in http://localhost:7357/src/hello.
js (line 5)
        ReferenceError: Can't find variable: _
            at sayHello (http://localhost:7357/src/hello.js:5)

here is my gruntfile:

module.exports = function(grunt) {

    grunt.initConfig({

        jshint: {
            all: ['src/**/*.js'],
            options: {
                globals: {
                    _: false,
                    $: false,
                    jasmine:false,
                    describe:false,
                    it:false,
                    expect: false,
                    beforeEach: false,
                    afterEach:false,
                    sinon:false
                },
                browser:true,
                devel: true
            }
        },

        testem: {
            unit: {
                options: {
                    framework: 'jasmine2',
                    launch_in_dev: ['PhantomJS'],
                    before_tests: 'grunt jshint',
                    serve_files: [
                        'node_modules/lodash/index.js',
                        'node_modules/jquery/dist/jquery.js',
                        'node_modules/sinon/pkg/sinon.js',
                        'src/**/*.js',
                        'test/**/*.js'
                    ],
                    watch_files: [
                        'src/**/*.js',
                        'test/**/*.js'
                    ]

                }
            }
        }

    });

    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-testem');
    grunt.registerTask('default', ['testem:run:unit']);

};

**Comment by cthulhu94401** [comment]
The issue was that I had made changes to the gruntfile, however I didn't restart the test runner.  I would suggest on page XV that you change the wording from "If you try launching the testem runner again, the test suite should now pass." to something along the lines of "You must restart the test runner now in order for the changes to the grunfile to take effect."

**Comment by Sharykhin** [comment]
I had the similar issue but with file Angular.js and there was the same error, but in the beginning i had the following grunt structure of unit:
```
unit: {
		options: {
			framework: 'jasmine2',
			launch_in_dev: ['PhantomJS'],
			before_tests: 'grunt jshint',
			serve_files: [
                'src/**/*.js',
				'test/**/*.js',
				'node_modules/lodash/index.js',
				'node_modules/jquery/dist/jquery.js',
				'node_modules/sinon/pkg/sinon.js'				
			],
			watch_files: [
				'src/**/*.js',
				'test/**/*.js'
			]
		}
	}
```

And to make it work properly I had to change the order of serve_files, like this:
```
unit: {
		options: {
			framework: 'jasmine2',
			launch_in_dev: ['PhantomJS'],
			before_tests: 'grunt jshint',
			serve_files: [                               
				'node_modules/lodash/index.js',
				'node_modules/jquery/dist/jquery.js',
				'node_modules/sinon/pkg/sinon.js',
                'src/**/*.js',
				'test/**/*.js'				
			],
			watch_files: [
				'src/**/*.js',
				'test/**/*.js'
			]
		}
	}
```

And this fixed my problem, but you should pay attention that the **grunt must be restarted**

**Comment by partizanos** [comment]
Same error here. I changed to search everything inside the lodash and jquery folders but it for chrome and NOT phantom browser since I still have the waiting message (see screenshot)
![bug2](https://cloud.githubusercontent.com/assets/5407188/13381383/fb562720-de5a-11e5-8e21-a37f0fb19601.PNG)

```
 testem: {
            unit: {
                options: {
                    framework: 'jasmine2',
                    launch_in_dev: ['PhantomJS'],
                    before_tests: 'grunt jshint',
                    serve_files: [
                        'node_modules/lodash/*.js',
                        'node_modules/jquery/**/*.js',
                        'node_modules/sinon/pkg/sinon.js',
                        'src/**/*.js',
                        'test/**/*.js'
                    ],
                    watch_files: [
                        'src/**/*.js',
                        'test/**/*.js'
                    ]
                }
            }
        }

```                

If someone has found a way to make this thing work please write I have not so much experience with phantom server or grunt yet

**Comment by partizanos** [comment]
Also this solution seems to work for both browsers:
```
                    serve_files: [
                        'node_modules/lodash/lodash.min.js',
                        'node_modules/jquery/dist/jquery.min.js',
                        'node_modules/sinon/pkg/sinon.js',
                        'src/**/*.js',
                        'test/**/*.js'

                    ],

```

**Comment by teropa** [comment]
The latest version of the book (update and change notes sent November 5) use Browserify and do not use Testem or Grunt. These problems should not be present with the new config.

**Comment by thavaamm** [comment]
Hi,

I too having same problem. Please help me.


module.exports = function(grunt) {
grunt.initConfig({

 jshint: {
   all: ['src/**/*.js'],
   options: {
    globals: {
       _: true,
       $: false,
       jasmine: false,
       describe: false,
       it: false,
       expect: false,
       beforeEach: false,
       afterEach: false,
       sinon: false
    },
    browser: true,
    devel: true
  }
 },

 testem: {
   unit: {
   options: {
   framework: 'jasmine2',
   launch_in_dev: ['PhantomJS'],
   before_tests: 'grunt jshint',
   serve_files: [
           'node_modules/lodash/index.js',
           'node_modules/jquery/dist/jquery.js',
           'node_modules/sinon/pkg/sinon.js',
           'src/**/*.js',
           'test/**/*.js'
            ],
   watch_files: [
           'src/**/*.js',
           'test/**/*.js'
           ]
   }
   }
 }


});


grunt.loadNpmTasks('grunt-contrib-jshint');
grunt.loadNpmTasks('grunt-contrib-testem');
grunt.registerTask('default', ['testem:run:unit']);

};

**Comment by teropa** [comment]
Refer to the latest versions of the book where this setup has changed. Grunt is no longer in use.

**Comment by thavaamm** [comment]
Thanks Teropa, but i don't have latest version of book. Could you share latest version pdf link here if its free.

**Comment by teropa** [comment]
If you have purchased the book at a previous time you should have received an email update with the latest version. If you haven't, please send your email address to tero@teropa.info and I'll check.

**Comment by thavaamm** [comment]
I brought it from my friend. I will check with him. Thanks Teropa for your reply.
