### ISSUE TITLE
P456 delete operator

### ISSUE THREAD

**Issue by nickvdyck** [teropa/build-your-own-angularjs#237]
I always considered delete to be an anti pattern (as you probably also know). Shouldn't you better advocate the use of null? delete slows things down a bit. And it doesn't seem to be necessary?

```
function processQueue(state) {
 var pending = state.pending;
 state.pending = null;
 _.forEach(pending, function(onFulfilled) { onFulfilled(state.value); });
}
```

https://github.com/teropa/build-your-own-angularjs/blob/master/src/q.js#L8

**Comment by teropa** [comment]
Using `null` in upcoming release, thanks
