### ISSUE TITLE
package.json needs fixing

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#239]
There is a `grunt-contrib-jasmine` package not used and a `grunt-contrib-watch` which is not there.

**Comment by Foxandxss** [comment]
Well, I don't think that the watch (and its task) is even needed.

**Comment by teropa** [comment]
Removed `grunt-contrib-jasmine` from package.json, and `grunt-contrib-watch` from Gruntfile.js. Thanks
