### ISSUE TITLE
xii - 'node_modules/sinon/pkg/sinon.js' would be in serve_files

### ISSUE THREAD

**Issue by Snger** [teropa/build-your-own-angularjs#244]
Chapter 0. Project Setup > xii Include Lo-Dash And jQuery

![image](https://cloud.githubusercontent.com/assets/1173747/7277176/0dfcd410-e941-11e4-8a00-a5da4b29aa32.png)

**Comment by teropa** [comment]
This was fixed in an earlier revision, thanks.
