### ISSUE TITLE
Page 326, typo, "clean slate"

### ISSUE THREAD

**Issue by fuyi** [teropa/build-your-own-angularjs#251]
"clean slate" should be "clean state"

**Comment by rkurbatov** [comment]
@fuyi http://www.schiefertafel-griffel.de/WebRoot/Store7/Shops/62508678/534B/C4C1/244D/B750/A6F3/C0A8/2BB9/0B92/DSCI8473.JPG - it called slate. Thought it is an error too.

**Comment by teropa** [comment]
"clean slate" is an idiom I wanted to use there. Modified the wording to make things clearer.

http://idioms.thefreedictionary.com/start+with+a+clean+slate
