### ISSUE TITLE
P548 BlobBuilder is deprecated

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#256]
The test doesn't pass on Chrome and it is because `BlobBuilder` is deprecated. Change the test to:

```javascript
it('does not serialize blobs for requests', function() {
  var blob = new Blob(['hello']);
  $http({
    method: 'POST',
    url: 'http://teropa.info',
    data: blob
  });
  $rootScope.$apply();

  expect(requests[0].requestBody).toBe(blob);
});
```

It pass in both runners.

**Comment by teropa** [comment]
This fails on my version of PhantomJS. Deferring this to an upcoming update of the setup chapter to latest versions. Likely resolved by that.

**Comment by dougeff** [comment]
I was just playing around with this.  This fix will work in the latest Chrome, Firefox, and Phantom:

	it('does not serialize blobs for requests', function () {
		var blob;
		try {
			blob = new Blob(['hello']);
		} catch (e) {
			var BlobBuilder = window.BlobBuilder || window.WebKitBlobBuilder || window.MozBlobBuilder || window.MSBlobBuilder;
			var bb = new BlobBuilder();
			bb.append('hello');
			blob = bb.getBlob('text/plain');
		}
		$http({
			method: 'POST',
			url: 'http://teropa.info',
			data: blob
		});
		$rootScope.$apply();
		expect(requests[0].requestBody).toBe(blob);
	});

**Comment by teropa** [comment]
Fixing along this lines, thanks
