### ISSUE TITLE
P11 - spec is failing with jasmine.createSpy().andReturn('something');

### ISSUE THREAD

**Issue by ckruszynsky** [teropa/build-your-own-angularjs#26]
When I run this example I'm getting a typeError : 'undefined' is not a function (evaluating 'jasmine.createSpy().andReturn('something').

If I remove the andReturn call this test will pass. 

Also, in the paragraph beneath the example you mention the following : 
"When the scope is digested our current implementation throws an
exception" and you explain that this is occurring because it's trying to invoke a non-existing listener. However, if I leave off the no-op function addition and just remove the andReturn call the test still passes.

**Comment by AlexCppns** [comment]
What am I doing wrong here: 
```
spyOn(window, 'FormData').and.Return({
   "append": jasmine.createSpy()
});
```
```
TypeError: 'undefined' is not a function 
```
I tried both and.Return and andReturn.

**Comment by fvanwijk** [comment]
Syntax for Jasmine 2 is `and.ReturnValue`.

(Key in double quotes also seems to be inconsistent style)
