### ISSUE TITLE
P677: work on page of "Web Components standard" is discontinued

### ISSUE THREAD

**Issue by quanhewan** [teropa/build-your-own-angularjs#270]
The link near the bottom of "Web Components standard", which is linked to this page:
http://www.w3.org/TR/components-intro/

And on this page it said:
"Work on this document has been discontinued and it should not be referenced. Numerous online resources about Web Components are available, including the Web Components wiki."

Maybe a link to another resource should be replaced with?

**Comment by teropa** [comment]
Thanks, now linking to [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components) instead.
