### ISSUE TITLE
P941: AngularJS API page does not exist

### ISSUE THREAD

**Issue by quanhewan** [teropa/build-your-own-angularjs#277]
Reaching the end of this page, [the link to the AngularJS documentation] (https://docs.angularjs.org/api/ng/service/%5Cprotect%20%5CT1%5Ctextdollar%20compile#transclusion-functions) does not exist.

Is it linked to the "Transclusion function" part [here] (https://docs.angularjs.org/api/ng/service/$compile#transclusion-functions)?

**Comment by teropa** [comment]
Yep. My production tools have problems with links that include anchors. Fixed with a shortener. Thanks!
