### ISSUE TITLE
Add information about testing framework

### ISSUE THREAD

**Issue by droidenator** [teropa/build-your-own-angularjs#285]
I'm looking at the sample of the introduction and the first chapter and noticed there's very little about your testing framework setup. By searching the PDF, I found references to Jasmine but it'd be nice to have a small section that detailed what testing setup you were using as far as framework, test runner, etc. 

I also see references to Jasmine in the Grunt file for the project so maybe this isn't necessary? It was just one thing that stood out to me as a little confusing at first that could use some clarification.

**Comment by ChrisEelmaa** [comment]
There is "Project Setup" section in the book which covers everything. I got myself running the same setup as Tero quite fast.

**Comment by teropa** [comment]
I'll revisit the setup soon and will see about describing Jasmine in more detail.

**Comment by teropa** [comment]
Extended the description(s) in Chapter 0 slightly. Users who aren't familiar with the frameworks can learn more by following the links provided, but the idea is indeed that you can get up and running by just following the steps in the book.
