### ISSUE TITLE
P908: wrong expectation in test

### ISSUE THREAD

**Issue by chekalin** [teropa/build-your-own-angularjs#294]
Test 'makes contents available to child elements' expects the following element in the book: 
expect(el.find('> [in-transclude] > [in-template]').length).toBe(1);
While transcluded content appears inside the template, thus expectation should be: 
expect(el.find('> [in-template] > [in-transclude]').length).toBe(1);

Also matches with code [here](https://github.com/teropa/build-your-own-angularjs/blob/master/test/compile_spec.js#L2986).

**Comment by teropa** [comment]
Fixed in #273. Thanks!
