### ISSUE TITLE
ensureSafeObject pg 255

### ISSUE THREAD

**Issue by frfancha** [teropa/build-your-own-angularjs#297]
-Testing for Object is done by obj === Object instead of
obj.getOwnPropertyNames || obj.getOwnPropertyDescriptor
since 1.3 (commit db713a1c1b2cf1a9f5f9b52a0e2481be3b0cf1be)

-Testing for window is done by obj.window === obj instead of
obj.document && obj.location && obj.alert && obj.setInterval
since same commit.

It's a detail.

**Comment by teropa** [comment]
Updated, thanks!
