### ISSUE TITLE
In Chapter 6, adding locals to parser causes the parser to break

### ISSUE THREAD

**Issue by Shuffguy** [teropa/build-your-own-angularjs#298]
I'm at the 'Locals' part of Chapter 6 and am changing the AST.Identifier case in the recurse statement, but when I've changed everything it tells me there's a parse error: unexpected number (please not I've changed all of the code as per the book's instructions, up to just before the Computed Attribute Lookup on page 223). I've looked over the code for hours but I can't see anything broken. Changing the case statement to how it is in the book breaks all of the parse tests.

**Comment by teropa** [comment]
Would it be possible for you to share your current code on GitHub or elsewhere so I could take a look?

**Comment by Shuffguy** [comment]
Sure! All my code is in this repository. 

https://github.com/Shuffguy/myangular

I'm stuck on the code right before Computed Attribute lookup, and the last thing I did was defining getHasOwnProperty on page 223. 

Sorry for not getting back to you before, I didn't see that you replied to me two weeks ago.

**Comment by Shuffguy** [comment]
I figured it out. It was a dumb bug. The lowercase L in the text looks a lot like a 1, almost indistinguishable, so I was using a 1 in the function constructor instead of L. In hindsight, since L obviously stands for local, a really stupid mistake of mine.
