### ISSUE TITLE
Initializing Watch Values

### ISSUE THREAD

**Issue by paul58914080** [teropa/build-your-own-angularjs#299]
Chapter 1. Page 11

In the test cases 'calls listener when watch value is first undefined' the assertion expect(scope.counter).toBe(1) should be expect(scope.counter).toBe(0). The example is quite misleading as we don't want the digest cycle to increment the watch counter when the value is undefined.

it('calls  the listener function when the watched value is undefined', function () {
            scope.counter = 0;
            var watchFn = function () {
                return scope.someValue;
            };
            var listenerFn = function (newValue, oldValue, scope) {
                scope.counter++;
            };
            expect(scope.counter).toBe(0);
            scope.$watch(watchFn, listenerFn);
            scope.$digest();
            expect(scope.counter).toBe(0);
        });

Correct me if I am wrong :)

**Comment by teropa** [comment]
We *do* want the listener to be invoked (and thus the counter) incremented even when the watched value is `undefined`. I've clarified the wording in the text. Thanks!
