### ISSUE TITLE
P721 -P725 (Termination Compilation)

### ISSUE THREAD

**Issue by FlemmingBehrend** [teropa/build-your-own-angularjs#309]
Some functions have attrs in their attrs list, even though attributes are first handled in the next chapter.

functions are:
 * applyDirectivesToNode (P723, P724)
    * Inside the function call is made to compile, also with attrs.
 * compileNodes (P725)
    * Inside the function call is made to collectDirectives, also with attrs.
    * Inside the function call is made to applyDirectivesToNode, also with attrs.

**Comment by teropa** [comment]
Fixing these, thanks.
