### ISSUE TITLE
P246

### ISSUE THREAD

**Issue by markselby9** [teropa/build-your-own-angularjs#310]
“In non-computed member accesses we’ll need to do a bit more work, as we won’t know the name of the property at parse time. Instead we’ll need to call ensureSafeMemberName at runtime, whenever the expression is evaluated.”
If I'm getting it right, the "non-computed member access" here should be "computed member access", because non-computed member access doesn't need to check at runtime.

**Comment by teropa** [comment]
Fixing, thanks
