### ISSUE TITLE
P60 'toBe' should read 'toEqual' for "uses the same array of old and new values on first run" test

### ISSUE THREAD

**Issue by tfowler-healthgrades** [teropa/build-your-own-angularjs#316]
The 'expect' should read 'toEqual' as opposed to 'toBe' for the test "uses the same array of old and new values on first run". (At least that's how I was able to get the test to pass...)

**Comment by tfowler-healthgrades** [comment]
Is anyone really looking at these? I realize the book is relatively new, but if it would help, I could create a fork, make the edits and then issue a pull request.

Really REALLY enjoying the book, btw! Nice work!

**Comment by Jack-X-Yang** [comment]
Hey, guys.I find the same problem.

**Comment by teropa** [comment]
The listener is called with the same `newValues` variable twice on the first run, so `toBe` should definitely work to compare them, and I prefer the stronger check, because it implies that as an app programmer you can actually check for `newValues === oldValues`.

    listenerFn(newValues, newValues, self);
