### ISSUE TITLE
PXI phantomjs should be phantomjs-prebuilt

### ISSUE THREAD

**Issue by daandvs** [teropa/build-your-own-angularjs#319]
I'm on Windows, so don't know if this issue also applies to OSX.

After doing `npm install phantomjs karma-phantomjs-launcher` and running `npm test` I got the following issue:

`07 02 2016 11:49:16.153:WARN [plugin]: Error during loading "E:\Learning\build your own angularjs\myangular\n
ode_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
07 02 2016 11:49:16.372:WARN [karma]: No captured browser, open http://localhost:9876/
07 02 2016 11:49:16.387:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
07 02 2016 11:49:16.387:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?`

I managed to solve this by doing `npm uninstall phantomjs --save-dev` and thereafter doing `npm install phantomjs-prebuilt --save-dev`

**Comment by garmeeh** [comment]
I can confirm this also happens on OSX and fixed it as above.

**Comment by itainoam** [comment]
Also fixed the problem for me. Thanks!

**Comment by teropa** [comment]
Updating to PhantomJS 2 and phantomjs-prebuilt in upcoming release, thanks
