### ISSUE TITLE
PXIII karma-browserify also requires watchify

### ISSUE THREAD

**Issue by daandvs** [teropa/build-your-own-angularjs#320]
I'm on Windows, don't know if this issue also applies on OSX.

`npm install --save-dev browserify karma-browserify` should be changed to `npm install --save-dev browserify watchify karma-browserify`. Otherwise, file changes while karma is running will not be picked up.

**Comment by teropa** [comment]
Updating to latest karma-browserify in upcoming release. They've switched to peer dependencies causing this issue. Thanks
