### ISSUE TITLE
grunt-contrib-testem to grunt-testem-mincer

### ISSUE THREAD

**Issue by 31H0B1eV** [teropa/build-your-own-angularjs#321]
- I have a lot of issues with 'Project setup' chapter and recommend change 'grunt-contrib-testem' lib to 'grunt-testem-mincer'. Please check official link to github repository ( https://github.com/inossidabile/grunt-testem-mincer ) from https://www.npmjs.com/package/grunt-contrib-testem .
 - Also i have issue with lodash (Cannot find '_') and Yes, i have setup path in options: {'serve_files'} also have tried 'src' and restarted grunt task. Maybe issue presented only in my environment (Ubuntu 15.10 with latest version node and other packages), but it can't load 'node_modules/lodash/index.js' use for example 'bower_components/lodash/dist/lodash.js' instead and this is make the trick.

**Comment by garmeeh** [comment]
Hey @31H0B1eV If you are still on the project set up it may be worth while downloading the updated version of the book as @teropa has removed the grunt dependency in favor of plain NPM build scripts.

This might help avoid any headaches later if you download the updated version at a later date.

**Comment by 31H0B1eV** [comment]
That's ok, i can make it work. In any case thanks.

**Comment by yairodriguez** [comment]
@31H0B1eV 
To solve that reference error about Lo-Dash, you can change `node_modules/lodash/index.js` to `node_modules/lodash/lodash.js`. That should be fixed.

**Comment by teropa** [comment]
The issues mentioned here are related to the pre-browserify project setup, closing.
