### ISSUE TITLE
P197

### ISSUE THREAD

**Issue by shibamo** [teropa/build-your-own-angularjs#324]
Error reported in lines below, looks the cause is that the map function in current lodash removed the third argument (see https://lodash.com/docs#map):

```
case AST.ArrayExpression:
  var elements = _.map(ast.elements, function(element) {
    return this.recurse(element); //Error happens here
  }, this);
  return '[]';
```
could change to this common way:
```
case AST.ArrayExpression:
  var that = this;
  var elements = _.map(ast.elements, function(element) {
    return that.recurse(element); 
  });
  return '[]';
```

**Comment by teropa** [comment]
Yes, this is due to LoDash 4 ugprade. Fixing in upcoming release, thanks
