### ISSUE TITLE
P281 typo

### ISSUE THREAD

**Issue by dansabadas** [teropa/build-your-own-angularjs#325]
I typo creeped here in the last expect line: there is a 'fales' instead of a 'false'.
At least it was still an 'e' instead of "god forbid" a 'u' :)

it('parses logical OR', function() {
expect(parse('true || true')()).toBe(true);
expect(parse('true || false')()).toBe(true);
expect(parse('fales || false')()).toBe(false);
});

**Comment by teropa** [comment]
Fixing, thanks
