### ISSUE TITLE
prerequisites forgotten

### ISSUE THREAD

**Issue by dansabadas** [teropa/build-your-own-angularjs#326]
in the file filter_spec.js you forgot to specify all the depoendencies at the beginning of the file
(parse and lodash _ in page 307) 
'use strict';

var _ = require('lodash');
var register = require('../src/filter').register;
var filter = require('../src/filter').filter;
var parse = require('../src/parse');

**Comment by teropa** [comment]
I don't believe `parse` or LoDash are ever used in `filter_spec.js` so there is no need to require them.
