### ISSUE TITLE
P338 unclear where to put tests

### ISSUE THREAD

**Issue by yseo4530** [teropa/build-your-own-angularjs#329]
It is unclear in which test block to put the tests for whether or not expressions are supported for $eval, $apply, and $evalAsync.

The last test implemented is on page 337 where the reader is instructed to add a test to the describe("$watchCollection") test block. I assume the tests for $eval, $apply, and $evalAsync go under the describe("digest") test block and not the describe("$watchCollection") test block, but it is unclear.

**Comment by teropa** [comment]
Clarifying these, thanks
