### ISSUE TITLE
P135: _.rest should be _.drop with newer versions of lodash

### ISSUE THREAD

**Issue by VisViva** [teropa/build-your-own-angularjs#337]
_.rest creates a function that invokes func with the this binding of the created function and arguments from start and beyond provided as an array. (https://lodash.com/docs#rest)

_.drop creates a slice of array with n elements dropped from the beginning. (https://lodash.com/docs#drop)

**Comment by teropa** [comment]
Latest versions of the book (since the release on May 1) use `_.tail` instead of `_.rest`.  Please see the change notes in the update email or contact me if you haven't received one.
