### ISSUE TITLE
Split Chapter 1

### ISSUE THREAD

**Issue by teropa** [teropa/build-your-own-angularjs#34]
Chapter 1 is quite long, and could be split into two:
1) Dirty checking
2) $eval/$apply/$evalAsync/$$postDigest/Phases

**Comment by fvanwijk** [comment]
Additional to splitting up the chapter, I suggest to split op the very large `describe` as well. Now there is a very large `describe('$digest', ...)` and later there is one added for `$watchGroup`. I expected multiple (sub)describes when reading the first chapter, concerning the scope methods.

For a better overview of the tests, you could make a nested `describe` per method: `describe('$eval', ...)`, `describe('$apply')`, etc.

**Comment by rkurbatov** [comment]
Fully agree all of you :)
1. Tests. $digest block is really too long and unlogical
2. Chapter 1 needs division. And, may be, some more explanation or examples in its second part, especially evalAsync. Sometimes it's hard to understand something if you don't know how to use it. 
3. Speed optimization may be given as a whole refactoring of cycle later.

Book is really wonderful!

**Comment by teropa** [comment]
Upcoming release splits chapter 1 and also splits some of the test code to separate describe blocks.
