### ISSUE TITLE
change _.rest to _.drop.

### ISSUE THREAD

**Issue by front-thinking** [teropa/build-your-own-angularjs#350]
page 135, inside $emit func, i think _.rest need to change to _.drop.

if use _.rest, the tests will fail. While _.drop not.

_.rest: https://lodash.com/docs/#rest
_.drop:https://lodash.com/docs/#drop

**Comment by front-thinking** [comment]
the same to #327 . tail instead.

**Comment by teropa** [comment]
Hi, these issues have been fixed in the latest versions of the book. If you have not received the email update, please send me a message at tero@teropa.info with your order information and I'l take care of it.
