### ISSUE TITLE
Move "Scheduling $evalAsync from Watch Functions" to appendix?

### ISSUE THREAD

**Issue by Sjors** [teropa/build-your-own-angularjs#45]
I haven't read beyond this yet, so I don't know if it's needed elsewhere in the book, but if not, I would move it away from chapter 1. It just makes things more complicated and the chapter is already pretty long. 

Just keep the phrase "Granted, this is something one should not do, since watch function are supposed to be side-effect free." and refer readers to the appendix if they care.

**Comment by teropa** [comment]
Not exactly moving this but I'm splitting chapter 1 so that the content is more manageable.
