### ISSUE TITLE
Make use of quotes consistent

### ISSUE THREAD

**Issue by teropa** [teropa/build-your-own-angularjs#60]

**Comment by fvanwijk** [comment]
Until P54 there are double quotes in the `it`s, after P54 I see a lot of single quotes in the `it`s.
Perhaps you could include a .jshintrc and .jscsrc file in the first chapter, which makes checking for code style stricter.

**Comment by tfowler-healthgrades** [comment]
Yes, please make this consistent in the next iteration/edit of the book. This is highly frustrating (no offense).

**Comment by teropa** [comment]
Fixing.
