### ISSUE TITLE
atal error: spawn ENOENT (sic)

### ISSUE THREAD

**Issue by JeffreyVest** [teropa/build-your-own-angularjs#88]
I followed the steps in the email sent out for the latest update to switch to Testem. I'm now getting the error "atal error: spawn ENOENT" when I try to run my default grunt task. I completely copy/pasted my Gruntfile.js from the linked version in the email (along with following the other steps).

**Comment by RuslanGrigoryev** [comment]
@jintoppy Thank you, man

**Comment by partizanos** [comment]
Same problem worked perfectly only small detail:
in file:
   node_modules\grunt-contrib-testem\node_modules\testem\lib\browser_launcher.js     
it was the line line 120 (not 123 as mentioned above)
   exe: 'phantomjs',       --->       exe: 'phantomjs.cmd',
